apiVersion: v1
kind: Service
metadata:
  name: unitygowebapi
  labels:
    app: unitygowebapi
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: unitygowebapi