---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "unitygowebapi"
  namespace: "default"
  labels:
    app: "unitygowebapi"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "unitygowebapi"
  template:
    metadata:
      labels:
        app: "unitygowebapi"
    spec:
      containers:
      - name: "unitygowebapi"
        image: "manonthesky/unitygowebapi:latest"
        imagePullPolicy: "Always"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "unitygowebapi-hpa"
  namespace: "default"
  labels:
    app: "unitygowebapi"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "unitygowebapi"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
